# Generated by Django 4.2.1 on 2023-05-19 23:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='uf',
        ),
        migrations.AddField(
            model_name='usuario',
            name='birthdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cnpj',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cro_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='gender',
            field=models.CharField(choices=[('MALE', 1), ('FEMALE', 2), ('OTHER', 3)], default='MALE', max_length=6),
        ),
        migrations.AddField(
            model_name='usuario',
            name='legal_name',
            field=models.CharField(default='legal name', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='uf_cro',
            field=models.CharField(default='NA', max_length=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('street_avenue', models.CharField(max_length=40)),
                ('number', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('uf', models.CharField(max_length=2)),
                ('additional_information', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
