# Generated by Django 4.2.1 on 2023-06-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_address_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='tb_personid',
            new_name='tb_person',
        ),
    ]
