# Generated by Django 4.2.1 on 2023-06-10 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_address_tb_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
