# Generated by Django 4.2.1 on 2023-06-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_person_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='uf',
            new_name='uf_cro',
        ),
    ]
